package = "luxdummy1"
version = "0.1.4"
lua = ">=5.1"

[description]
summary = ""
maintainer = "rodamaral"
labels = [  ]

# [source]
# url = "https://github.com/rodamaral/$(PACKAGE)/archive/refs/tags/v$(VERSION).zip"
# dev = "git+https://github.com/rodamaral/$(PACKAGE).git"

[source]
url = "https://github.com/rodamaral/$(PACKAGE)"
tag = "v0.1.4"

[dependencies]
argparse = "0.7.1-1"
inspect = "3.1.3-0"
lua-cjson = "2.1.0-1"
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "none"

[build.modules]
"luxdummy1" = "src/main.lua"
"luxdummy1lua" = "lua/main.lua"

[build.install.lua]
"luxdummy1" = "src/main.lua"
"luxdummy1lua" = "lua/main.lua"
