package = "luxdummy1"
version = "0.1.7"
lua = ">=5.1"

[description]
summary = ""
maintainer = "rodamaral"
labels = [  ]

[source]
url = "https://github.com/rodamaral/$(PACKAGE)/archive/refs/tags/v$(VERSION).zip"
dev = "git+https://github.com/rodamaral/$(PACKAGE).git"
dir = "luxdummy1-0.1.7"
# dir = "$(PACKAGE)-$(VERSION)-1"
# dir = "$(PACKAGE)-$(VERSION)"

[dependencies]
argparse = "0.7.1-1"
inspect = "3.1.3-0"
lua-cjson = "2.1.0-1"
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"

[build.modules]
"luxdummy1" = "src/main.lua"
"luxdummy1_lua" = "lua/main.lua"
